version: '3.8'

services:
  # 1. 백엔드
  backend-server:
    container_name: backend-server-c
    build:
      context: ./backend-server # 폴더명 확인
      dockerfile: Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/sports_db
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword
      # DB 호스트 이름을 컨테이너 이름(mariadb)으로 설정해야 함

  # 2. 데이터베이스
  mariadb:
    image: mariadb:11.4 # 최신보다는 LTS 버전 명시 권장
    container_name: mariadb-c
    restart: always
    ports:
      - "3306:3306"
    command: --lower_case_table_names=1
    environment:
      - DB_HOST=mariadb
      - MARIADB_ROOT_PASSWORD=rootpassword
      - MARIADB_DATABASE=sports_db
      - MARIADB_USER=myuser
      - MARIADB_PASSWORD=mypassword
    volumes:
      - mariadb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      retries: 5

  # 3. 프론트엔드 (유저)
  frontend-user:
    container_name: frontend-user-c
    build:
      context: ./frontend-user
      dockerfile: Dockerfile
    ports:
      - "5173:80" # 호스트:컨테이너
    depends_on:
      - backend-server

  # 4. 프론트엔드 (관리자)
  frontend-admin:
    container_name: frontend-admin-c
    build:
      context: ./frontend-admin
      dockerfile: Dockerfile
    ports:
      - "5174:80"
    depends_on:
      - backend-server

volumes:
  mariadb-data: